CREATE TABLE POLL (
  ID    BIGINT CONSTRAINT PK_POLL PRIMARY KEY,
  TITLE VARCHAR(256) NOT NULL
);

CREATE TABLE POLL_CHOICE (
  ID          BIGINT CONSTRAINT PK_CHOICE PRIMARY KEY,
  CHOICE_TEXT VARCHAR(512) NOT NULL,
  VOTES       INTEGER      NOT NULL,
  POLL_ID     BIGINT       NOT NULL,

  CONSTRAINT FK_POLL FOREIGN KEY (POLL_ID) REFERENCES POLL (ID)
);
ALTER TABLE PUBLIC.POLL_CHOICE DROP PRIMARY KEY;
ALTER TABLE PUBLIC.POLL_CHOICE ALTER COLUMN ID IDENTITY;
ALTER TABLE PUBLIC.POLL_CHOICE ADD CONSTRAINT PK_POLL_CHOICE_ID PRIMARY KEY (ID);


